// Code generated by protoc-gen-go.
// source: rrfp/rrfp.proto
// DO NOT EDIT!

/*
Package rrfp is a generated protocol buffer package.

It is generated from these files:
	rrfp/rrfp.proto

It has these top-level messages:
	Message
	Head
	Body
	ExampleEchoRequest
	ExampleEchoResponse
*/
package rrfp

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Hd *Head `protobuf:"bytes,10,opt,name=hd" json:"hd,omitempty"`
	By *Body `protobuf:"bytes,20,opt,name=by" json:"by,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetHd() *Head {
	if m != nil {
		return m.Hd
	}
	return nil
}

func (m *Message) GetBy() *Body {
	if m != nil {
		return m.By
	}
	return nil
}

type Head struct {
	SesionNo string `protobuf:"bytes,10,opt,name=sesionNo" json:"sesionNo,omitempty"`
	UniqueId string `protobuf:"bytes,20,opt,name=uniqueId" json:"uniqueId,omitempty"`
}

func (m *Head) Reset()                    { *m = Head{} }
func (m *Head) String() string            { return proto.CompactTextString(m) }
func (*Head) ProtoMessage()               {}
func (*Head) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Body struct {
	// Types that are valid to be assigned to MsgType:
	//	*Body_ExampleEchoRequest
	//	*Body_ExampleEchoResponse
	MsgType isBody_MsgType `protobuf_oneof:"msgType"`
}

func (m *Body) Reset()                    { *m = Body{} }
func (m *Body) String() string            { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()               {}
func (*Body) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isBody_MsgType interface {
	isBody_MsgType()
}

type Body_ExampleEchoRequest struct {
	ExampleEchoRequest *ExampleEchoRequest `protobuf:"bytes,10,opt,name=example_echo_request,json=exampleEchoRequest,oneof"`
}
type Body_ExampleEchoResponse struct {
	ExampleEchoResponse *ExampleEchoResponse `protobuf:"bytes,20,opt,name=example_echo_response,json=exampleEchoResponse,oneof"`
}

func (*Body_ExampleEchoRequest) isBody_MsgType()  {}
func (*Body_ExampleEchoResponse) isBody_MsgType() {}

func (m *Body) GetMsgType() isBody_MsgType {
	if m != nil {
		return m.MsgType
	}
	return nil
}

func (m *Body) GetExampleEchoRequest() *ExampleEchoRequest {
	if x, ok := m.GetMsgType().(*Body_ExampleEchoRequest); ok {
		return x.ExampleEchoRequest
	}
	return nil
}

func (m *Body) GetExampleEchoResponse() *ExampleEchoResponse {
	if x, ok := m.GetMsgType().(*Body_ExampleEchoResponse); ok {
		return x.ExampleEchoResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Body) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Body_OneofMarshaler, _Body_OneofUnmarshaler, _Body_OneofSizer, []interface{}{
		(*Body_ExampleEchoRequest)(nil),
		(*Body_ExampleEchoResponse)(nil),
	}
}

func _Body_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Body)
	// msgType
	switch x := m.MsgType.(type) {
	case *Body_ExampleEchoRequest:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExampleEchoRequest); err != nil {
			return err
		}
	case *Body_ExampleEchoResponse:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExampleEchoResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Body.MsgType has unexpected type %T", x)
	}
	return nil
}

func _Body_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Body)
	switch tag {
	case 10: // msgType.example_echo_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExampleEchoRequest)
		err := b.DecodeMessage(msg)
		m.MsgType = &Body_ExampleEchoRequest{msg}
		return true, err
	case 20: // msgType.example_echo_response
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExampleEchoResponse)
		err := b.DecodeMessage(msg)
		m.MsgType = &Body_ExampleEchoResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Body_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Body)
	// msgType
	switch x := m.MsgType.(type) {
	case *Body_ExampleEchoRequest:
		s := proto.Size(x.ExampleEchoRequest)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Body_ExampleEchoResponse:
		s := proto.Size(x.ExampleEchoResponse)
		n += proto.SizeVarint(20<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ExampleEchoRequest struct {
	Msg string `protobuf:"bytes,10,opt,name=msg" json:"msg,omitempty"`
}

func (m *ExampleEchoRequest) Reset()                    { *m = ExampleEchoRequest{} }
func (m *ExampleEchoRequest) String() string            { return proto.CompactTextString(m) }
func (*ExampleEchoRequest) ProtoMessage()               {}
func (*ExampleEchoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ExampleEchoResponse struct {
	Msg string `protobuf:"bytes,10,opt,name=msg" json:"msg,omitempty"`
}

func (m *ExampleEchoResponse) Reset()                    { *m = ExampleEchoResponse{} }
func (m *ExampleEchoResponse) String() string            { return proto.CompactTextString(m) }
func (*ExampleEchoResponse) ProtoMessage()               {}
func (*ExampleEchoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Message)(nil), "rrfp.Message")
	proto.RegisterType((*Head)(nil), "rrfp.Head")
	proto.RegisterType((*Body)(nil), "rrfp.Body")
	proto.RegisterType((*ExampleEchoRequest)(nil), "rrfp.ExampleEchoRequest")
	proto.RegisterType((*ExampleEchoResponse)(nil), "rrfp.ExampleEchoResponse")
}

func init() { proto.RegisterFile("rrfp/rrfp.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x2a, 0x4a, 0x2b,
	0xd0, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x92, 0x23, 0x17,
	0xbb, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x90, 0x14, 0x17, 0x53, 0x46, 0x8a, 0x04, 0x97,
	0x02, 0xa3, 0x06, 0xb7, 0x11, 0x97, 0x1e, 0x58, 0xa5, 0x47, 0x6a, 0x62, 0x4a, 0x10, 0x50, 0x14,
	0x24, 0x97, 0x54, 0x29, 0x21, 0x82, 0x2c, 0xe7, 0x94, 0x9f, 0x52, 0x19, 0x04, 0x14, 0x55, 0xb2,
	0xe3, 0x62, 0x01, 0xa9, 0x03, 0xaa, 0xe1, 0x28, 0x4e, 0x2d, 0xce, 0xcc, 0xcf, 0xf3, 0xcb, 0x07,
	0x9b, 0xc2, 0x19, 0x04, 0xe7, 0x83, 0xe4, 0x4a, 0xf3, 0x32, 0x0b, 0x4b, 0x53, 0x3d, 0x53, 0xc0,
	0xa6, 0x00, 0xe5, 0x60, 0x7c, 0xa5, 0x0d, 0x8c, 0x5c, 0x2c, 0x20, 0xc3, 0x84, 0x7c, 0xb8, 0x44,
	0x52, 0x2b, 0x12, 0x73, 0x0b, 0x72, 0x52, 0xe3, 0x53, 0x93, 0x33, 0xf2, 0xe3, 0x8b, 0x52, 0x81,
	0x0a, 0x8a, 0x4b, 0xa0, 0x4e, 0x92, 0x80, 0x58, 0xeb, 0x0a, 0x51, 0xe1, 0x0a, 0x54, 0x10, 0x04,
	0x91, 0xf7, 0x60, 0x08, 0x12, 0x4a, 0xc5, 0x10, 0x15, 0xf2, 0xe7, 0x12, 0x45, 0x33, 0xad, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0x15, 0xea, 0x0b, 0x49, 0x2c, 0xc6, 0x41, 0x14, 0x00, 0xcd, 0x13, 0x4e,
	0xc5, 0x14, 0x76, 0xe2, 0xe4, 0x62, 0xcf, 0x2d, 0x4e, 0x0f, 0xa9, 0x2c, 0x48, 0x55, 0x52, 0xe3,
	0x12, 0xc2, 0x74, 0x87, 0x90, 0x00, 0x17, 0x33, 0x50, 0x01, 0xd4, 0xef, 0x20, 0xa6, 0x92, 0x3a,
	0x97, 0x30, 0x16, 0x0b, 0x30, 0x15, 0x26, 0xb1, 0x81, 0xe3, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x81, 0x98, 0x13, 0x2c, 0xa6, 0x01, 0x00, 0x00,
}
